site_name: GDP Labs SRE Team
site_description: GDP Labs infrastructure documentation
theme:
  name: material
  custom_dir: !ENV [THEME_DIR, "material"]
  logo: assets/images/gdplabs.png
  palette:
    primary: light blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
plugins:
  - minify:
      minify_html: true
nav:
  - Home: index.md
  - Projects:
    - GLAIR:
      - Buzz Chat: projects/glair/buzzchat.md
      - Buzz Socmed: projects/glair/buzzsocmed.md
    - KASKUS:
      - Common Tasks: projects/kaskus/tasks.md
  - FAQ: faq.md
